dist: xenial
language: generic
addons:
  apt:
    packages:
    - patchutils
install:
- python -m pip install --user pygments restructuredtext-lint
script:
- shellcheck diffcmd
- restructuredtext-lint --encoding=UTF-8 README
- prove -v
- PATH=".:$PATH"
- diffcmd -h

# vim:ts=2 sts=2 sw=2 et
