dist: trusty
sudo: false
language: generic
addons:
  apt:
    packages:
    - python-docutils
    - python-pygments
    - shellcheck
script:
- shellcheck diffcmd
- private/check-rst

# vim:ts=2 sts=2 sw=2 et
