dist: trusty
sudo: false
language: generic
addons:
  apt:
    packages:
    - shellcheck
install:
- python -m pip install --user docutils pygments
script:
- shellcheck diffcmd
- private/check-rst

# vim:ts=2 sts=2 sw=2 et
