#!/bin/sh

# Copyright © 2012-2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
usage() printf 'Usage: %s -n IDENT [-U N] -- COMMAND [ARG...]\n' "${0##*/}"
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}/diffcmd
context=3
while getopts 'hn:U:' opt
do
    case "$opt" in
        h) usage; exit 0;;
        n) ident="$OPTARG";;
        U) context=$((OPTARG));;
        *) exit 1;;
    esac
done
shift $((OPTIND - 1))
if [ -z "${ident-}" ] || [ $# -eq 0 ]
then
    usage >&2
    exit 1
fi
cache="$cachedir/$ident"
temp=$(mktemp "$cache".XXXXXX)
if "$@" > "$temp"
then
    touch -a "$cache"
    diff -U "$context" "$cache" "$temp" | filterdiff --strip=999 --remove-timestamps
    mv -f "$temp" "$cache"
else
    xs=$?
    rm -f "$temp"
    exit $xs
fi

# vim:ts=4 sw=4 et
